name: check

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt update
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install -yq --no-install-recommends pre-commit
      - name: Execute Pre-commit Hooks
        run: pre-commit run --show-diff-on-failure --color=always --all-files
